### PR TITLE
Adding in get by UserID to controller, services, and testing

### PR DESCRIPTION
**Pull request by JennicaLeClerc**

### CODE REVIEW

**Review by Justin-Sherfey — APPROVED** [review]

**Review by LutherNa — CHANGES_REQUESTED** [review]
The function in the UserController is named wrong (says findByUserName, should be findByUserID). 
The function in the UserService returns a complete user object, including the hashed password. 
Consider an echo-user get request that pulls the active user from the JWT attached to the request. 
Consider a DTO for user information without password attached.

**Review by Justin-Sherfey — CHANGES_REQUESTED** [review]
what nathan said

**Review by Justin-Sherfey — APPROVED** [review]
dto added and filename changed

**Comment by johcrean** [comment]
Changes made @LutherNa

**Review by LutherNa — APPROVED** [review]
Changes accepted. Request APPROVED.

**Review by AaronLitton — APPROVED** [review]
Looks good

**Pull request merged**
