### PR TITLE
Dev groups test

### PR DESCRIPTION
**Pull request by RPHaynes**

### CODE REVIEW

**Review by johcrean — APPROVED** [review]
Looking good

**Review by AaronLitton — APPROVED** [review]
Tests look functional and comments don't seem to have overarching descriptions but passable

**Review by Justin-Sherfey — APPROVED** [review]

**Review by JennicaLeClerc — APPROVED** [review]
Jennica being pedantic

**Review by cphoy1337 — APPROVED** [review]
Small comments at the top of the tests would be appreciated later but it looks good.

**Pull request merged**
