### PR TITLE
Extra documentation for files

### PR DESCRIPTION
**Pull request by Justin-Sherfey**

### CODE REVIEW

**Review by LutherNa — COMMENTED** [review]
No substantive changes seen, ref to documentation and Jennica for full approval, ping me if she's late.

**Review by AaronLitton — APPROVED** [review]
Looking good on the comments

**Review by LutherNa — APPROVED** [review]

**Review by JennicaLeClerc — APPROVED** [review]
Stand in for Documentation

**Review by johcrean — COMMENTED** [review]
Nice

**Pull request merged**
